/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface': '#191c1e',
        'tertiary-container': '#001a42',
        'primary-fixed': '#dae2fd',
        'on-tertiary-fixed': '#001a42',
        'on-surface-variant': '#45464d',
        'on-secondary': '#ffffff',
        'surface-tint': '#565e74',
        'outline-variant': '#c6c6cd',
        'secondary-container': '#6cf8bb',
        'on-error-container': '#93000a',
        'surface': '#f7f9fb',
        'tertiary-fixed-dim': '#adc6ff',
        'surface-container-high': '#e6e8ea',
        'primary-fixed-dim': '#bec6e0',
        'secondary-fixed-dim': '#4edea3',
        'on-primary-fixed-variant': '#3f465c',
        'surface-variant': '#e0e3e5',
        'secondary-fixed': '#6ffbbe',
        'on-secondary-container': '#00714d',
        'surface-bright': '#f7f9fb',
        'on-primary-container': '#7c839b',
        'surface-container-highest': '#e0e3e5',
        'on-tertiary': '#ffffff',
        'inverse-surface': '#2d3133',
        'on-tertiary-container': '#3980f4',
        'primary': '#000000',
        'on-secondary-fixed-variant': '#005236',
        'on-error': '#ffffff',
        'on-background': '#191c1e',
        'surface-dim': '#d8dadc',
        'on-tertiary-fixed-variant': '#004395',
        'tertiary': '#000000',
        'inverse-on-surface': '#eff1f3',
        'background': '#f7f9fb',
        'on-primary-fixed': '#131b2e',
        'secondary': '#006c49',
        'primary-container': '#131b2e',
        'tertiary-fixed': '#d8e2ff',
        'outline': '#76777d',
        'error': '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed': '#002113',
        'surface-container-low': '#f2f4f6',
        'inverse-primary': '#bec6e0',
        'on-primary': '#ffffff',
        'error-container': '#ffdad6',
        'surface-container': '#eceef0',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'gutter': '24px',
        'xl': '64px',
        'margin': '32px',
        'lg': '40px',
        'sm': '12px',
        'base': '8px',
        'xs': '4px',
        'md': '24px',
      },
      fontFamily: {
        'label-bold': ['Inter'],
        'h1': ['Inter'],
        'body-lg': ['Inter'],
        'h3': ['Inter'],
        'h2': ['Inter'],
        'body-sm': ['Inter'],
        'body-md': ['Inter'],
        'sans': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'label-bold': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'h1': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'h3': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'h2': ['30px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
